### ISSUE TITLE
Katharsis is cluttering logs by printing exception stack traces in warning

### ISSUE THREAD

**Issue by mitch2na** [katharsis-project/katharsis-framework#158]
Title says it all, io.katharsis.dispatcher.RequestDispatcher is logging all exception stack traces at warning level even when there is an exception mapper dedicated to this.

**Comment by remmeier** [comment]
I probably should rather comment here:

could we work with log levels instead of hiding exceptions?

WARN for exceptions with mappers and ERROR for exceptions without mapper seems appropriate. People then see the exceptions and can choose to ignore them if they like too.

I think the exception handling needs some work in general. People will have a hard time when only getting a response status/message. And browsers currently only show a blank page in case of problems.

Katharsis by default provides a KatharsisExceptionMapper. This one covers a wide variety of exceptions, many of those are errors where a stacktrace would be quite helpful. Katharsis itself may should increase the log level for testing.

**Comment by chb0github** [comment]
Actually, I discovered that the exception mapper is getting invoked twice.
Side note

**Comment by mitch2na** [comment]
@remmeier I dont think adding a WARN level is appropriate if the developer has explicitly created an ExceptionMapper with the given ExceptionClass. This will only create more of a headache on the developer / operations if they have to tweak the logging levels to prevent stack traces from being printed by default. Seems like we are trying to adhere to a the case where a developer has not done there due diligence by logging an exception in their mapper.

**Comment by remmeier** [comment]
yes, logging in the mapper sounds good to me too. 

KatharsisExceptionMapper may choose the log level based on the error number, with any 5xx code being printed as ERROR.

**Comment by mitch2na** [comment]
Cool, just made the fix. If anyone wants to merge it feel free.

**Comment by chb0github** [comment]
Can you reference the pr?

**Comment by mitch2na** [comment]
https://github.com/katharsis-project/katharsis-framework/pull/159
