### ISSUE TITLE
relationship filtering doesn't work

### ISSUE THREAD

**Issue by chb0github** [katharsis-project/katharsis-framework#160]
When doing query param filtering as per [spec](http://jsonapi.org/format/#fetching-includes)
See PR #161 
I get:

```
GET /api/projects/?include=tasks.location HTTP/1.1
HOST: localhost:8080
accept: application/vnd.api+json
```

```
{
  "errors": [
    {
      "status": "400",
      "title": "Request parameters error",
      "detail": "Malformed filter parameter: "
    }
  ]
}
```

**Comment by pjweisberg** [comment]
I'm not familiar with the history of it, but this is definitely the result of a conscious choice.

https://github.com/katharsis-project/katharsis-framework/blob/develop/katharsis-core/src/main/java/io/katharsis/queryParams/QueryParams.java#L298

In fact, it looks like every JavaDoc comment in that file begins with "<strong>Important!</strong> Katharsis implementation differs form JSON API..."  So _all_ query parameters are in katharsis-format, not JSON API format, not just the `includes` parameter.

The Katharsis version of the above request would be `/api/projects/?include[projects]=tasks.location`

**Comment by pjweisberg** [comment]
I did find two different bugs aside from the documented spec-noncompliance, though.

1) If you ask it to include "tasks" it will also include "tasks.location" (probably because location is marked @JsonApiIncludeByDefault), even though the spec says it MUST NOT include resources other than the ones specified, if any were specified at all.

2) The URI I gave above actually _doesn't_ work (tasks and locations aren't included) the first time.  If you request a specific object instead of a collection (`/api/projects/123?include[projects]=tasks.location`), then the tasks and locations will be included.  If you later request the collection with the includes, they will be included.  I haven't investigated yet why this happens.

**Comment by pjweisberg** [comment]
On closer inspection, 2 is the result of the way findOne and findAll are implemented in the spring-boot-simple-example version of ProjectRepository, not anything to do with the way includes are handled.

**Comment by chb0github** [comment]
relates to #113

**Comment by remmeier** [comment]
the given request will work when querySpec instead of QueryParams is used, there is a initial PR in the documentation project that descrives this: 

https://github.com/katharsis-project/katharsis-docs/blob/adnovum_extensions/source/user-docs.rst

goal is to be json api compliant with this
