### ISSUE TITLE
2.7 changelog release notes

### ISSUE THREAD

**Issue by Ramblurr** [katharsis-project/katharsis-framework#171]
The changelog doesn't have any information about the 2.7 release.

Keeping these up to date is important for users to follow the project, to know what is going on, what's changed, etc.

**Comment by chb0github** [comment]
I had no idea how to get generate then. Happy to add

On Thu, Oct 20, 2016, 4:30 AM Casey Link <notifications@github.com> wrote:

The changelog doesn't have any information about the 2.7 release.

Keeping these up to date is important for users to follow the project, to
know what is going on, what's changed, etc.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/katharsis-project/katharsis-framework/issues/171>, or mute
the thread

**Comment by Ramblurr** [comment]
Yea, I'm not sure either.

Related to #65, we should create a "Release checklist" guide to be followed so all the things that need updating, get updated.

**Comment by mohlek** [comment]
defining milestones would help too.
Since we are mainly working on the next release version and don't need to maintain different main line , all pr should should be assigned with the current active milestone.

**Comment by chb0github** [comment]
I am in favor of ditching the dev branch, merging into master and
automating the build/release process. Every new feature is a new release

**Comment by remmeier** [comment]
that sounds great to me. But we should make sure the test/sonar/coverage setup is working for all modues (https://github.com/katharsis-project/katharsis-framework/issues/142)
