### ISSUE TITLE
Streamline resource definitions and redesign internal repository model for more reuse between submodules

### ISSUE THREAD

**Issue by hibaymj** [katharsis-project/katharsis-framework#259]
I believe Katharsis should provide a mechanism to support non-repository style data sources.  A concrete example of the type of data source to support would be myBatis, as the framework allows you to bind extremely complex queries to objects without the need to work around lazy loading and multiple query concerns.

As Katharsis stands now, the framework is fundamentally biased towards repository driven ORM frameworks or data sources.  This creates many hurdles throughout implementation of resource models, as well as requiring redundant definitions for the relationship between objects.  The internal relationship and include repositories (internal repos) present an even larger difficulty in implementing, as the resource model definition would likely not include the ID required for lookup.  In the case of an RDBMS, a non repository ORM such as myBatis can leverage extremely performant queries to populate all of a resources data, while the repository model could require multiple trips to the RDBMS or cache, as well as additional processing for filtering, pagination, and sparse fields.  All of the repository model concerns can be accomplished by a properly designed query, executed within a single transaction, and require as little additional processing as necessary.

Additionally, during resource scanning, certain information is collected which should be able to substantially cut down on boilerplate code and classes, allowing a much leaner resource definition process.  These changes would also be required to support the non-repository style data sources, as the internal repos api no longer would fit the needs of the required functionality.  With these changes to the metadata information in resource classes, a default handler could be constructed for each resource abstracting the need for the internal repos from the API designer.

I have included an initial design or concept for comment on how I think this functionality should be implemented.

```
@JsonApiResource(
        type = "TestResource",
        relation = {ConvertResource.class, MigrateResource.class},
        //OR
        relation = {
                @JsonApiRelation(
                        type = ConvertResource.class,
                        idAttribute = "id",// which ID for the related resource,if not present assumes collection
                        templated = true,
                        include = "id != null" //EL or other scripting code
                ),
                @JsonApiRelation(
                        type = MigrateResource.class,
                        idAttribute = "id",// which ID for the related resource,if not present assumes collection
                        templated = true,
                        include = "id != null" //EL or other scripting code
                )
        },
        meta = {MetaInformation.class},
        //OR
        meta = {
                @JsonApiMeta(
                        type = MetaInformation.class,
                        templateValues = {
                                @JsonApiTemplateValue(
                                        name = "resourceType",
                                        value = "resourceParameterValue"
                                )
                        },
                        templated = true,
                        include = "id != null" //EL or other scripting code
                )
        }
)
public class TestResource {

    @JsonApiId // still need this
    private Long id;

    //could use JsonIgnore for jackson or @Transient for jpa or just transient as I think both respect the modifier
    private transient String dontSend;

//    Not necessary, as it is inherently an attribute if the type is not defined as a resource
//    @JsonProperty
    private String name;

//    Not necessary, as an iterable or [] can be determined via reflections so there is no need to declare this,
//    and the type can be derived from the concrete classes
//    @JsonApiToMany
    private List<AnotherTestResource> anotherTestResource = new ArrayList<>();
}
```

**Comment by chb0github** [comment]
Hey Micheal,

Katharsis as a project does need a serious rethink. The JSONApi comes from
Ember.js and they have a slick design for taking any crazy data you're
dealing with an normalizing it. I am all ears on how:

Significant changes to the code base can be made when:
1) Everyone is a part time volunteer.
2) Many of the changes desired would completely destroy backward
compatibility.
3) a huge portion of code could be eliminated by moving to java 8 (see #2)

You're not the only one who has a beef with the code base. I would love to
see the annotation method for defining repositories just go away and become
strictly interface driven. And, Everything that's needed to produce the
attributes portion of the payload can be determined from reflection -- no
need to implement all these repositories with boilerplate code.

thoughts?

**Comment by Avonsoft** [comment]
I hesitate to say I have beef with the code base.  I simply have identified and diagnosed a shortcoming of the current implementation in regards to functionality and ease of use, and spent some time coming up with a potential solution.

I am submitting this issue as a means to gather feedback on the design, as well as locate any potential 'gotchas' I missed through my inspection.  My proposal tries to balance the fact that this is OSS, entirely volunteer based and therefor I am attempting to find the best way to interface the solution, while providing backwards compatibility and the least amount of time invested.  This functionality is something I intend to develop, regardless of its inclusion into the framework.  My hope is with enough appropriate feedback, we can come to a consensus on the best solution to develop, which can be integrated back into the fold.

To address your number concerns in order:
1) I think the above paragraph covers this.
2) I don't intend to remove any sort of backwards compatibility, at the onset I only want to provide an alternative.
3) Your experience with the code base is of course, much greater than mine, and the inclusion of filters would certainly provide a means to reduce boilerplate, I am not sure if this would increase the opinionated nature of the framework towards any particular servlet provider.  I don't see java 8 mentioned in the linked issue, but lamda functions could certainly obviate the need for repositories for filtering and spare fieldsets.  However, I can't see at this time how it would address sorting, pagination concerns, the relationship handling, or a declarative and self sufficient model.

To solve most of this, I plan to extend the information gathered about the classes in the initial reflection pass, use the linked information to build appropriate resource trees. I will then create the repositories for the rest of the framework to use referencing the resource tree structure, and extended with the capability to ignore their signature parameters instead interrogating the source object for the responses.

I suggested the boilerplate reduction was necessary, because it seems counter-intuitive to take a small step, when it is not much more effort to take a large one.

I'll reiterate, I plan to add support of additional functionality by interfacing appropriately and gradually providing additional alternatives.  If this functionality should break or be insufficient for a user's needs, I wholly intend to allow them the ability to override and replace the repository functionality in the exact same way as it is currently done.

**Comment by remmeier** [comment]
well, what we all know for sure I guess is that Katharsis used in a wide range of scenarios. Already me I used it in a varierty of environments from exposing JPA, basic repository with QuerySpec.apply, accessing ElasticSearch or as wrapper exposing third-party services. And plenty of other people used in other environments. At least for me it works very well in many scenarios, in particular with the module api allowing to reconfiure already many things. I would say no single approach will satisfy all use cases. And even harder to convince people of that. As such it is also not possible to completely redesign the system for a new use cases or break compatiblity. In particular the later is important and a very strict requirement that I'm able to contribute here. 

Instead we should continue along the current path of improving modularity and flexiblity in katharsis-core. The current interfaces we have ResourceRepository(V2) and RelationshipRepository(v2) closely resemble the JSON API specification. They match the things that can be requested from a JSON API endpoint. As such they are quite well suited for a "katharsis-core". They can be consider to be a low-level API. They do what they suppose to do, but not more. They don't provide the comfort maybe necessary for some use cases. Naturally, there are some issues. In particular the serialization part needs a bit of (incremental) cleanup. Which then further increases the flexiblity of katharsis-core, like letting the interface repositories to directly return JSON API documents and let them do whatever they please.

Now, having thoses core interfaces. Additional katharsis modules can build upon that and provide additional feature, convience, etc. Once the low-level interface is called, they are free to do whatever they please. katharsis-jpa is good example. It makes use of none of the Katharsis annotations, etc. The user does not have to implement any repositories. But it is able to expose JPA entities on top of katharsis-core. The ResourceRepositoryBase class is a simple other example. It elimnates virtually all the boiler-plate for a given class of use cases (with some further improvement possible). A single method implementation suffices to expose a resource as read-only JSON API endpoint including relations, How cool is that :-) 

I would say that is the path we should continue. In the context of this ticket it means to setup a katharsis-mybatis as a first step. I can follow the same path as katharsis-jpa, meaning defining a MyBatisModule, registering its generic repositories and resource information builders. The MyBatisRepository are then the entrypoint to the new world proposed here. So it will prepare and forward calls to the new API or whatever necessary, read the proposed annotations, etc. If it has an efficient way of fetching content with MyBatis, great. Similarly as fir katharsis-jpa we can extend/modularize/make katharsis-core more flexible at the places needed to support this while maintain what we have. So this are rather incremental improvements to katharsis-core. In a second step, if the endeavor is successul, we can split up katharsis-mybatis into two modules, one mybatis specifc and one more generic allowing to reuse its patterns in scenarios other than mybatis. The approach will let people choose the Katharsis modules they seem best suited for their use cases.

I can help with the katharsis-core imporvement parts.

On the katharsis-core side:
- we already planned a cleanup of the package structure to clearly differentiate internal and public API. 
- I should/must keep its size or shrink a bit.
- I agree with the interface-based approach. The pure annotation-based repositories could be moved into a module or deprecated depending on their popularity.
- once we have the package cleanup, we continue with the serialization part. There is no magic involved here and it is limited to internal API. So small, non-dangerous incremental improvements should do.
- we can extend the ResourceRegistry/Information API and its usage along the way of this ticket.

**Comment by Avonsoft** [comment]
As this seems to be the preferred location for discussing issues related to the repository design, I'll take the rest of the discussion here.

I reiterate, I don't advise an individual breaking change, interfaces can be put in place to add the ability to keep functionality exactly as is.  It is far easier to **ADD** constraints to an interface or implementation then it is to **REMOVE** constraints, and the repository model is extremely constricting as it requires either a bespoke caching layer, or some other mitigation steps to function when Katharsis is not responsible for a resources composition.

Modularity and flexibility are generally keywords for customization, and using them to describe the direction of development implies a higher use of touch on individual sub modules, or individual implementations.  A library such as Katharsis' strongest benefit is the ability to abstract away concerns from a developers plate.  However we seem to be focusing more on writing code for specific module implementations, then code which is reused requiring much less code in specific implementations.

Now here is the biggest rub with what you assert.  Matching an external representation with an internal design flies in the face of years of engineering knowledge.  Katharsis and other frameworks should absolutely match the external representation of JsonApi without fault, however nothing about how that is accomplished is dictated by the specification.  There is no reason to say it can't resemble the representation, but when there is identified #259 #121 #200 reason for this not to happen then maybe something could change.

I have previously said the JPA module is a perfect example of the type of integration and developer effort required to utilize Katharsis, but JPA is also built around the Repository model so the ease of integration comes as no surprise.

The concern is to abstract the core processing of Katharsis to the core, in a way where Repository model, and everything else can equally take advantage of its processing without concession.

Finally Katharsis-core shouldn't shrink or maintain size, it should consume and subsume functionality from the modules until the absolute bare minimum of unique code is in each sub-project in order for the core to function.  This functionality should be integrated, and not duplicated between each project.

**Comment by remmeier** [comment]
well the topic here is still on a fairly abstract level and raises various questions about deseign, performance and restrictions. We used in various environments. No problems whatsoever. So if there is a concrete issue. Please create a branch, setup an example app and we can have a look at it how to resolve that. Otherwise this discsussion here is not going anywhere unfortunately, I think.

on an architectual level the packages will be cleaned up next. Some of the old stuff removed resp. deprecated. After that the limiations of resources have to be actual Java classes/DTOs/beans will fall.

**Comment by Avonsoft** [comment]
I'll concede there are potential workarounds, and certainly value in performing a wrapped incremental approach to supporting core reuse.  The initial points I wrote didn't seem to take into account sorting and filtering functionality, which would necessitate enhancing the mybatis query engine regardless of the model chosen.  Thus, it would reduce some of the weight of the design considerations in favor of making more sweeping changes.

However the initial motivation was to keep the framework close enough to the object model where an existing mybatis service layer project could include Katharsis-mybatis and stand up a nearly config free JsonApi server.  The concept behind this was to include that type of functionality, as a carrot to increase the adoption pool to the project.  As well as a means to begin allowing a better approach in the future.  However, this doesn't necessarily result in the best designed resource definitions, and at some point the work can't be done by the framework.
