### ISSUE TITLE
properly support inheritance

### ISSUE THREAD

**Issue by remmeier** [katharsis-project/katharsis-framework#278]
there are a varierty of inheritance related issues and possible improvements in katharsis:

- proper inclusions of relations of super and subtypes
- sorting, filtering, selection of attributes on subtypes
- discovery of subtypes in katharsis-client
- discovery of relationship repositories on the server-side
- ...

**Comment by Avonsoft** [comment]
Lets step back, while this would be awesome to have I don't think JsonApi itself has support for inheritance.  I would tread carefully down the realm of non-spec code within the framework.  Any effort down the line of adding inheritance support should probably be proceeded by at least a rough cut at an extension spec for the base specification, and aim development for the moving target while its being discussed.

**Comment by chb0github** [comment]
Well,

I suppose caution isn't entirely unreasonable. However, without the ability
to support inheritance, in Java you would have to have 1 object with a lot
of null fields which would differ per type. There is nothing in the spec on
this matter and I don't see a reason they would even bother addressing it -
The only distinction in a wireline format is the addition/subtraction of
fields in the payload; that's it. But, I don't remember specifically,
katharsis looks at the class that has the resource annotation and tries to
marshal into that. Which is entirely unnecessary; Jackson has built in
support for polymorphism.

I think a definite PoC is in order. If it doesn't work, lets express why

**Comment by Avonsoft** [comment]
The issue is not that jackson can't do it, its how do you properly advertise this to your clients when the specification does not detail how to do so.

```
public class Person{
  private String firstName;
  private String lastName;
}

public class Teacher extends Person{
  private String classRoom;
}

public class Student extends Person{
  private String class;
}
```
I have a resource Persons, how do I advertise to my client consumer which class it should expect?  That is a really simple contrived issue with running off and adhoc writing support for inheritance without an underlying specification to reference.  You are really running the risk of duplicating the exact same issue of the QueryParams vs QuerySpec.  Sure it might be functional and useful when implemented, but is Katharsis supposed to be a JsonApi implementation or simply pay tribute to the spec?

**Comment by Sandmania** [comment]
From JsonApi spec point of view, this could be an extension http://jsonapi.org/extensions/

**Comment by chb0github** [comment]
Hmm, interesting argument you make.

The spec is silent on this which is understandable. So implementing it or
not does not violate the spirit or the letter of the spec.

Without this functionality you would have to have an entirely different
resource per subtype. And right now, Katharsis doesn't like subtypes.


From a REST / http standpoint, limiting the resource body shape has no
precedence. PUT and POST will take data of any shape.

On Mon, Jan 23, 2017, 7:55 PM Michael Hibay <notifications@github.com>
wrote:

The issue is not that jackson can't do it, its how do you properly
advertise this to your clients when the specification does not detail how
to do so.

public class Person{
  private String firstName;
  private String lastName;
}

public class Teacher extends Person{
  private String classRoom;
}

public class Student extends Person{
  private String class;
}

I have a resource Persons, how do I advertise to my client consumer which
class it should expect? That is a really simple contrived issue with
running off and adhoc writing support for inheritance without an underlying
specification to reference. You are really running the risk of duplicating
the exact same issue of the QueryParams vs QuerySpec. Sure it might be
functional and useful when implemented, but is Katharsis supposed to be a
JsonApi implementation or simply pay tribute to the spec?

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/katharsis-project/katharsis-framework/issues/278#issuecomment-274698954>,
or mute the thread

**Comment by remmeier** [comment]
I think the json api spec is ok in this regard. All resources are identified by type/id. So querying a base resource can deliver arbitrary subtypes. katharsis-meta makes use of inheritance and it seems to work quite well already. But proper testing and some minor improvements (like how to handle polymorph relationships) to katharsis core would be good. 

The only conceptual issue I have seen so far is that katharsis-client is not able to map back resourceTypes to java classes without the use of a discovery mechanism resp. explicitly registering all resource classes.

**Comment by chb0github** [comment]
The katharsis client is an aid to development not a requirement - I mean, you don't **have** to use katharsis-client (and, non java projects won't). The katharsis client should never be the limiting factor on the server/framework - which is what Katharsis the project is _selling_

Polymorphic payloads is damn handy.

**Comment by hibaymj** [comment]
If we take the extension approach (which is still currently undefined) we could first write the specification, and when some form of member consensus is reached we could start working down that path.

@remmeier I don't think that is necessarily the only way to solve the reverse mapping problem, it's quite possible to declare the inheritance structure within your representation definition.  The issue is how do you accomplish this without _requiring_ the use of another specific media type?  If we use ALPS as the application profile, there is no core support for polymorphism, as the model is designed to be message oriented, not object oriented.  So speaking about  inheritance within an ALPS document would feel odd, in that case it would probably make more sense for 'extends' and 'extendedBy' or 'transcludes' and 'transcludedBy'.  It is free to be extended within the meta section, but by definition this is not interoperable.  ALPS also has the issue of not having defined an extension mechanism to allow you to broadcast the extension format.

However, schema.org has very concisely solved this problem for the machine-operable hypermedia space that search engines love, and they declare the hierarchies which are entirely runtime discoverable.  However, it is tightly bound to HTTP and it will strongly couple the affordance definition with the resource format.

**Comment by remmeier** [comment]
the points you mentioned is a reason why I setup katharsis-meta. An easy to understand, pure JSON API, close to Java/OOP model of katharsis. ALPS et. al. sometimes seem to be a bit detached from reality. But I would not mind support in katharsis either (as long as we don't enforce once single format, but are open to multiple ones).

Not sure whether I should integrate that here resp. add support in katharsis-client. But it would be one approach. Maybe there is a simpler, more basic one.

**Comment by hibaymj** [comment]
Alps requires a translation layer for your individual protocol (HTTP, CoAP... etc.) to take the constraints and map it to a particular message type.  However, the aloof nature you describe as detached from reality is part of what makes it better than schema.org.  It is addressable to more solution spaces than just HTTP.

I am extremely against any heavy or complex solution within a **framework** utilizing the meta fields in any specification, jsonapi included.  The reason for this is extremely _practical_, simply I'm sick of repeating myself and about 15,000 other developers who have been this way before.  Standards allow us to once and done a solution, meta or customized non-standard solutions have no place within a framework.  They simply are not interoperable, and defeat the principle of having the framework in the first place.  Solutions in katharsis meta now need just as much a priori knowledge about that meta, eliminating the benefit of hypermedia and the standard itself, because you need to know when a server is a _katharsis_/jsonapi server.

It isn't a pedantic argument, as soon as you start doing this you have forked, and every step down that road is at least one likely many more **you** need to take to get back to standard if you don't just PUSH the standard in the right direction first.  This doesn't even mention the amount of work anyone who utilized your framework now needs to take to get back to unconditionally compliant.  Prototyping for proposal adoption is one thing and encouraged, releasing functionality within catchall extension blocks is quite another.

This framework is about JsonAPI but we have an undefined extension protocol so create an issue / task to WRITE the jsonapi extension format proposal, drive that through, and then we can talk about how to do this.

**Comment by remmeier** [comment]
well I have nothing about standards, but we already concluded that Swagger is problematic to say at least. You brought up "there is no core support for polymorphism, as the model is designed to be message oriented, not object oriented.", so ALPS is problematic as well. Should we still find anything that seems suitable, perfect. Otherwise it likely still makes sense to support one or the other.

katharsis-meta is not comparable in that regard. It is an optional module and provides direct 1:1 information about all repositories and resources. It matches the backend model perfectly, no limitations, no indirections. It is suitable to automate e.g. frontend development tasks done within the same application. It is not intended for a general purpose, standardized exchange format of meta information.

**Comment by hibaymj** [comment]
Entirely agreed.  To your last point, it makes it katharsis only, regardless of it conforming to JsonAPI standards, there is no way to discover or negotiate for it.

I may have added a lot of detail to the previous post, but the conclusion sentence is by far the most important.  To your point, we could also state we need to propose changes / additions to ALPS for support.  Regardless the theme of the post still stands, the way we as active framework developers in these specs need to act is to push the standards first to support what we have identified as missing features _now_ and before building out the tooling.  I am not saying we can't build out the tooling _before_ adoption or approval, we just need to have a working copy of the standard or proposal to work against to keep our work honest.  If we do that, fixing any final changes before adoption will be orders of magnitude simpler.

**Comment by remmeier** [comment]
no longer needed
