### ISSUE TITLE
New Annotation For Relationship Resources

### ISSUE THREAD

**Issue by mitch2na** [katharsis-project/katharsis-framework#299]
Per discussion with 3.0 making a change to deprecate `@JsonApiToOne` ,`@JsonApiToMany`, ` @JsonApiLookupIncludeAutomatically`, and ` @JsonApiIncludeByDefault`. Current functionality will be as follows:

* Create a single relationship annotation called ` @JsonApiRelation`
* ` @JsonApiRelation` is lazy by default
* ` @JsonApiRelation` has a serialize field with serialize =(SerializeType.LAZY, ONLY_ID, and EAGER). LAZY is serialize only when requested with include param. ONLY_ID is serialize the ids in the resources relationship section but not the included section. EAGER is serialize the ids in the relationship and included section.
* ` @JsonApiRelation` has an additional field "lookup" of type LookupIncludeBehavior (NONE, AUTOMATICALLY_WHEN_NULL, AUTOMATICALLY_ALWAYS). The default is AUTOMATICALLY_WHEN_NULL. But it can be overridden by a property application-wide.

**Comment by chb0github** [comment]
Interesting

**Comment by mitch2na** [comment]
@chb0github Open for discussion, just figured i would write it down. Will wait to get approval on this

**Comment by Avonsoft** [comment]
I like where this is going, as I have previously made comments and concerns down this path.  I am actively investigating this, but the concerns I have with your proposal are as follows:

1. This really only works with repository model data access.  Which almost always comes with the side effect of lots of extra data access overhead.  Because of this efficiently managing data access would be very difficult.
2. The base case should not be required to be annotated.  Through package scanning we should be able to know which are relations (other top level resources) and which aren't.  The default should be to include all relations, unless programmatically and intentionally excluded or breaking the chain of inclusion.
3. The core of Katharsis is fundamentally intended to be re-written to support different use case scenarios.  I feel like this type of annotation would be a boon to Katharsis with JPA, but any non repository driven ORM or webservice based data source would likely suffer performance tuning issues as the implementation is shoehorned into this model.

**Comment by mitch2na** [comment]
In regard to number 2, I definitely agree that it would be easier to not require the relationship annotation.

Could you explain a bit more about number 3? How would this add performance issues with non JPA resources?

**Comment by chb0github** [comment]
We need to have a total rethink on how we do this repository thing. The
whole use of Annotations and interfaces both is a mess

**Comment by Avonsoft** [comment]
@mitch2na Regarding #3 its a boon to repository type formats, like JPA.  Non repository formats such as Mybatis would suffer either weird performance drops via multiple(db hits, ws calls....etc.), or have a difficult time integrating with the design paradigm of the per resource repository structure.

@chb0github Right, we seem to have gone over this in a few issues, but I'm still not convinced the annotation vs interface is necessarily the cause.  I believe the issue stems from the conceptual approach to data retrieval, and whether a resource model is intended to be complete on its own.  From all of my experience, adding multiple trips by dividing up the composition of a resource to multiple repositories screams wrong.

**Comment by remmeier** [comment]
I would say it got a bit off-topic. That repository model discussions should be handled somewhere else. But just two points: 
- The current interfaces closely resemble what  JSON API specifies. As such it is quite ok as a low-level contract that various things can build upon.
- Repositories have all the flexibility they desire. A single repository call can load all the relations as well in a single query if they desire to. Or Katharsis can takeover and load related data with multiple repositories calls (and such like multiple db or whatever queries). This is controlled by the lookup behavior. There is no performance issue here. The application has  to design their repositories properly.

Now to the actual topic. Katharsis 3.0 will not be breaking. We will deprecate various things and throw it out with Katharsis 4.0 to give applications time to migrate. The idea of introducing @JsonApiRelation as in the description is great. The current ones are hard to understand and have the wrong defaults. AnnotationResourceInformationBuilder can be extended by the new annotation. And the old ones can be deprecated. The new annotations includes

- a field "serialize " as suggested: LAZY, ONLY_ID, EAGER
- a field "lookup" of type LookupIncludeBehavior (NONE, AUTOMATICALLY_WHEN_NULL, AUTOMATICALLY_ALWAYS). The default is AUTOMATICALLY_WHEN_NULL. But it can be overriden by a property application-wide.

**Comment by remmeier** [comment]
potentially it could also be a 3.1 feature. To some degree I would like to make the package refactoring and then do the 3.0 instead of holding off for further feature. There is already plenty of things that should be released.

**Comment by Avonsoft** [comment]
@remmeier The repository topic is directly related to how you flag the object model for the resources.  I do agree that portion of the discussion is better elsewhere, which is why I linked to the issue I created.  However, it does not imply the discussion doesn't have implications on this topic.  To your points on the repository topic, I'll respond in the other issue.

Regarding the AnnotationResourceInformationBuilder as the base for this inclusion, I think based on my previous points of introspection and intelligent defaults, this would not be appropriate as it would violate the second point in my original response; the default case should not need to be annotated.  If this method was to be taken, I think a refactor of that class would be in order, both in name and base functionality, as the class is still fundamentally annotation driven.

**Comment by mitch2na** [comment]
Agree this has gotten off topic.

@Avonsoft I agree with @remmeier that what you are talking about is a limitation with json api spec.

@remmeier I'm fine with waiting on this feature until 3.1 and keeping 3.x in compliance with 2.x. Is there anything we need to remove with this major release? Might want to use this time to clean up any deprecated code in 2.x

**Comment by Avonsoft** [comment]
@mitch2na @remmeier If you are truly asserting the specification in any way directs or advises internal design constraints, I would be happy to review any linked documentation you can provide to support the assertion.  Perhaps this is off topic, and then in this case I would agree with the original release inclusion @remmeier suggested of 4.0, as it would allow the appropriate time to discuss the issue which would have substantial impact on how this feature should be implemented.

**Comment by remmeier** [comment]
added to develop_v3 branch
