### ISSUE TITLE
Reading the content(body) of a patch request

### ISSUE THREAD

**Issue by giulio90** [katharsis-project/katharsis-framework#335]
Is it possible to read the content of a patch request? I would like to process the request body myself. I tried using the method getEntityStream in ContainerRequestContext, however, since this is an InputStream and is read by Katharsis before the findOne method is accessed, the InputStream returns empty. Any thoughts on this? I am using Katharsis with Jaxrs.

**Comment by Koshux** [comment]
I have been encountering the same issue when attempting to obtain the request message body from the 'ContainerRequestContext'.  As one may realise, the JAX-RS message access modifier is set to private and thus cannot obtain the request body.  When trying to obtain the JAX-RS message from the 'request.getEntityStream()', the result is an empty string since it has already been read from the KatharsisFilter.
![katharsis_jax-rs_issue](https://cloud.githubusercontent.com/assets/21141573/23548115/515fa560-0006-11e7-8e7b-272d6ad2325a.PNG)

**Comment by hibaymj** [comment]
This could be addressed as part of a fix with #354 by adding a getRawMessageBody() to the RequestContext.

This would require a buffering wrapper to be placed around the raw jax-rs / spring request facades to allow for multiple access.

However, there are security implications to allowing downstream access to the raw content in this way, as it would expose data beyond the intentionally placed Firewalled implementations.  To add this to #354 warrants a discussion to carefully determine how to proceed if at all.

**Comment by chb0github** [comment]
In my mind, if you're trying to directly access the body in a patch request (and expecting katharsis to enable that) then you shouldn't be using katharsis. Katharsis is fairly opinionated by design. You don't have ready access to the body because, well, those who use frameworks like katharsis don't really care about it - they need the payload marshaled and processed.

Can you explain the use-case that is motivating this need?

**Comment by remmeier** [comment]
there is a DocumentFilter in Katharsis 3

**Comment by giulio90** [comment]
Yes, I upgraded to Katharsis 3 recently and used the DocumentFilter which allows me to read the body before it reaches the repository. However is it possible to access the same information from inside the repository itself? (similar to ContainerRequestContext).
