### ISSUE TITLE
Inclusion of multiple relationships stopped working in 2.8.2

### ISSUE THREAD

**Issue by weaselmetal** [katharsis-project/katharsis-framework#372]
A request like this used to work in 2.6:

    GET /api/pets/5?include[pets][]=owner.children&include[pets][]=owner.parents

This would return both relationships of pet with id=5 in the ``included`` section of the json response.

As of katharsis 2.8.2, with the same request, I get *only one*``owner.relationship`` at a time.

In the`PetsResource`, the `children` and `parents` fields are annotated with `@JsonApiLookupIncludeAutomatically`.

In Katharsis 2.8.2 these still work fine:

    GET /api/pets/5?include[pets][]=owner.children
    GET /api/pets/5?include[pets][]=owner.parents

...but trying to get both included at the same time will only include data for one relationship, never more.

There seems to be some caching going on when the ``owner`` relationship is resolved which avoids correct inclusion of another relationship of ``owner``.

I did my debugging in [``io.katharsis.resource.include.IncludeLookupSetter.setIncludedElements(ResourceInformation, Iterable, List<String>, QueryAdapter, RepositoryMethodParameterProvider)``](https://github.com/katharsis-project/katharsis-framework/blob/katharsis-build-2.8.2/katharsis-core/src/main/java/io/katharsis/resource/include/IncludeLookupSetter.java#L109)
around line 109.

**Comment by Ramblurr** [comment]
This seems to affect 3.0/master too. I've [pushed a test case](https://github.com/katharsis-project/katharsis-framework/commit/af434379dcc17e70ff78610f19403392ff879abc) that replicates this issue.

In the test case the query is for `/users/1` with

```
include[users]=group
include[users]=group.projects
include[users]=group.memoranda
```

The expected `Response` should have 3 items in the `included` array, of types `group`, `projects`, and `memoranda`, but there is always only 2.

**Comment by remmeier** [comment]
likely it is related to the parameter handling, not the actual inclusion processing. The inclusion lookup setter starts with the returned (root) resources and from there recursively iterates over all the relationships. Every <resource,relationship> is checked exactly once. So it will move to group and from there to projects and memoranda given that it correctly processed those inclusion parameters. 

on the QuerySpec side that is working for sure, because e.g. katharsis-meta makes heavy use of it. Maybe there is a gap in QueryParams.

**Comment by Ramblurr** [comment]
This definitely seems to be a bug introduced during the 2.8 query params refactor.

**Comment by remmeier** [comment]
I have a quick look at the test case later today, no need to worry.

**Comment by remmeier** [comment]
just the test was broken, inclusions work perfectly fine for that test case.

@weaselmetal: I would give katharsis 3.0 a try since the entire thing has been rewritten in that area. fairly confident that it is now working as it is supposed to. Altough issues related to QueryParams are not impossible, as the QuerySpec part is better tested.

**Comment by remmeier** [comment]
if it is not working with 3.0, please reopen again

**Comment by remmeier** [comment]
actually you may want to give the master branch a try, as there are some further improvements not in the 3.0.0 release.

**Comment by Ramblurr** [comment]
@remmeier we (@weaselmetal and I) can't upgrade to 3.0/master for several reasons yet:

* Resource cannot contain parameterized type #350
* And other things that cause exceptions when I run the 3.0-ified version of our app, that I haven't had time to investigate
* we can't use java 8 yet (I know... I know...), so master is out for now

Is a fix for 2.8.x not on the table?

**Comment by remmeier** [comment]
- actual source compatiblity is on Java 7 (changed that back since we had more than one complaint)
- I probably would go directly from 2.6 => 3.0 once time allows it. 3.0 is not really much new, but a lot of cleanup and testing compared to 2.8.2.
- I don't prevent anyone from doing a patch  for 2.8.x. But not from my side. 3.0 is for me the patched up 2.x. The inclusion behavior was one of the areas that was fairly messed up in past.

**Comment by weaselmetal** [comment]
Hum, that's rather bad news. 2.8 contained many bug fixes we were looking forward to get.
Neither upgrading nor downgrading is very appealing currently.

**Comment by remmeier** [comment]
3.0/master = 2.8 + clean up serializer + cleaned up  inclusion behavior + many more test cases + various fixes + no major new features like QuerySpec, etc.

there is no point in dragging around that 2.8.x version any longer.

**Comment by weaselmetal** [comment]
Meaning there are no changes to our codebase required @remmeier ?
