### ISSUE TITLE
Support isXy and getXy boolean attribute naming

### ISSUE THREAD

**Issue by remmeier** [katharsis-project/katharsis-framework#395]
currently it seems to only properly support "is". It should support "get", "is" and "has" as prefix.

**Comment by RapidTransit** [comment]
I was just about to post this, look at Jodd BeanUtil's for an example, also Collection and Map Types not everyone uses setters.

**Comment by Ramblurr** [comment]
Additionally, also "getFoo" should be supported as per the JavaBeans spec:

Section 8.3.2: Boolean properties (emphasis added):
> In addition, for boolean properties, we allow a getter method to match the pattern:
```public boolean is<PropertyName>();```
This “is<PropertyName>” method may be provided instead of a “get<PropertyName>” method, **or it may be provided in addition to a “get<PropertyName>” method**.

**Comment by Ramblurr** [comment]
@RapidTransit What do you mean by the following?

> also Collection and Map Types not everyone uses setters.

I don't understand :)

**Comment by Ramblurr** [comment]
So after some thought I think this should be discussed.

`is` and `get` prefix, I'm all for that, it follows the Java Bean spec.

`has` prefix, I'm opposed to it, as it doesn't follow the Java Bean specification, and as a FOSS framework I think Katharsis should strive to uphold the standards when it can.

Also, given how Katharsis currently parses the resource classes using our reflection tools, this class introduces an ambiguity:

```java
Long id;

Long getId() { return id; }

@JsonIgnore
boolean hasId() { return id == null; }
```

That actually exists now in katharsis-meta.

The problem is that katharsis parses fields and getters separately, then groups them together by their java bean spec property name. The above code would group all three of the field and two methods together. Then the last would be discarded due to the `JsonIgnore`, taking the id field with it.

This results in a `ResourceIdNotFoundException: Id field not found in class:` error.

The happens only by supporting `has` as a valid getter name.

**Comment by chb0github** [comment]
Support what Jackson supports so there is no ambiguity. This is a feature right? Not a bug/complaint?

**Comment by RapidTransit** [comment]
@Ramblurr Suppose a POJO like this

```java

public class SomePojo {

    protected String a;
    protected List<String> b = new ArrayList<>();
```
The intent is that the field `b` should not be explicitly mutated, rather just the underlying collection, there's a few reasons for this, if the collection is a specific type, to avoid passing a refrence to a list, modifying the outside of the POJO, but the most important is laziness lol

**Comment by Ramblurr** [comment]
@RapidTransit Is this part of the java bean specification?

@chb0github yes it is a feature. Obviously we can't support every arcane Jackson feature, but if we re-use their annotations then the behavior should be as similar as possible.

**Comment by remmeier** [comment]
no longer needed
