### ISSUE TITLE
Improve logging in case of exceptions

### ISSUE THREAD

**Issue by remmeier** [katharsis-project/katharsis-framework#95]
There is currently barely any use of loggers. In particular in case of exceptions they get translated to http status codes where most information about the cause (the stacktrace) gets lost. For example, the RequestDispatcher and KatharsisFilter catch(Exception) clauses should log the error somewhere.  A constraintViolationException is something expected and shows up from time to time. Internal server errors should not and would be more of an ERROR. Maybe with WARN because the severity is unclear?

**Comment by reegnz** [comment]
Looking at the JSON-API spec, I saw that an Error MAY contain an ID. what would you think about generating an ID for an error, putting that both in the log message and the error object as well?

I regularly do this pattern where I generate a UUID at the error handling and log it, and also put it in the response, so that I can find the error message (and/or stacktrace) in the logs when I get an error report with the ID.

**Comment by remmeier** [comment]
logging added to the exception mappers, and test cases have a logback setup. Looks now much better.

@reegnz : logging is handled by the exception mappers. So if they make use of the id and log it, if they like to.
